### ISSUE TITLE
Steps for Evaluation on test data and Inference on single input image.

### ISSUE THREAD

**Issue by Zeeshan75** [Ipsedo/MARLClassification#4] opened 2023-03-19 05:14 UTC
Hi @Ipsedo, 

I have gone through your code, and I am able to train the model on the custom dataset, but while doing the inference and evaluation, I am confused with the eval options and main options, state_dict.

it would be helpful if you provide the steps or documentation for doing inference on a single image and testing the model on test dataset.

Thanks in advance.

**Comment by Ipsedo** [comment] 2023-03-20 07:22
Hi @Zeeshan75,

Can you provide me the command line you attempt to run for evaluation and/or inference?
I don't have my laptop next to me but after the work day I will send you command sample to run inference and evaluation. 

I am curious to know which dataset you trained the model on :)

**Comment by Zeeshan75** [comment] 2023-03-20 14:22
Hi I'm working on the skin cancer classification dataset with image resolution 224×224

**Comment by Ipsedo** [comment] 2023-03-20 20:46
Is this dataset open data ? If yes can you share a link ?

About the inference command :
```
python -m marl_classification --run-id infer_resisc45 -a 16 --step 16 --cuda infer --images /path/to/NWPU-RESISC45/airport/airport_015.jpg /path/to/NWPU-RESISC45/beach/beach_009.jpg --json-path ./out/resisc45_actor_critic/marl.json --state-dict-path ./out/resisc45_actor_critic/models/nn_models_epoch_49.pt --class2idx ./out/resisc45_actor_critic/class_to_idx.json -o ./out/infer_resisc45_actor_critic
```

This command will load `./out/resisc45_actor_critic/marl.json` as neural network hyper-parameters, `./out/resisc45_actor_critic/models/nn_models_epoch_49.pt` as neural network parameters and `./out/resisc45_actor_critic_final/class_to_idx.json` for the class to index mapping. Those 3 files are created when training.

For testing it is quite similar except that `--images` option is replaced by `--image-path` which needs to be the path of your image dataset. Beceause it will be loaded as a torchvision ImageFolder dataset, the image directory tree must be like below :
```
/path/to/dataset/
             |-- class_1/
             |    |-- img_1.png
             |    |-- ....
             |-- class_2/
             |    |-- img_2.png
             |    |-- ...
             |-- ...
```
and in the command line : `--image-path /path/to/dataset`.

Let me know if it was helpful for you.

**Comment by Zeeshan75** [comment] 2023-03-23 17:54
Hi @Ipsedo 

Pls find below link for the skin_cancer dataset we have used:
https://drive.google.com/drive/folders/17g6zFSbCNXTV3VaDKop73W7Cn-NJlTO7?usp=sharing

here is the drive link for modified code and dataset:
https://drive.google.com/drive/folders/15e79yCTh50GVrB9bNjT6LIiLsCB6X4nY?usp=share_link

We are using the cnn architecture as below in the CNNftExtractor file, 
<
class SkinCancerCnn(CNNFtExtract):

    def __init__(self, f: int) -> None:
        super().__init__()

        self.__seq_conv = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=(3, 3), padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(16, 32, kernel_size=(3, 3), padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            nn.Conv2d(32, 64, kernel_size=(3, 3), padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
            />
            
Here is the command I am using for model training 
<
$ python -m marl_classification -a 10 --step 16 --cuda --run-id train_skin_cancer train --action [[1,0],[-1,0],[0,1],[0,-1]] --ft-extr skin_cancer --batch-size 8 --nb-class 2 --img-size 256 -d 2 --nb 192 --na 192 --nd 16 --f 12 --nm 64 --nlb 256 --nla 256 --nb-epoch 50 --learning-rate 1e-4 --eps 1.0 --eps-dec 0.99995 -o ./out/resisc45
/>

but getting the below issue in the LSTM layer: 

/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 6 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
  0% 0/61 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/__main__.py", line 348, in <module>
    main()
  File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/__main__.py", line 296, in main
    train(main_options, train_options)
  File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/train.py", line 187, in train
    pred, log_proba, _ = detailed_episode(
  File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/environment/episode.py", line 85, in detailed_episode
    agents.step(img_batch, eps)
  File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/environment/agent.py", line 177, in step
    h_t_next, c_t_next = self.__networks(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/networks/models.py", line 87, in forward
    return self.__networks_dict[op](*args)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/networks/recurrents.py", line 41, in forward
    h_next, c_next = self.__lstm(u, (h, c))
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/rnn.py", line 1194, in forward
    ret = _VF.lstm_cell(
RuntimeError: input has inconsistent input_size: got 56 expected 24

Pls let us know what we can change
Thank you.

**Comment by Ipsedo** [comment] 2023-03-23 21:33
What did you return in the overrided method `out_size` of `SkinCancerCnn`? Should be something like `64 * (f // 8) ** 2`.
Other question : did you use pytorch `Flatten` module to transform the image patch into a vector after the convolution layers?

This weekend I will add your dataset and its convolutional network on the branch `actor-critic` (the more recent branch).

**Comment by Ipsedo** [comment] 2023-03-25 19:51
I've pushed on `master` (which is now merged with `actor-critic` branch) the dataset and module classes. Everything works great I can't reproduce your error.

The training command :
```
python -m marl_classification -a 16 --step 16 --cuda --run-id train_skin_cancer train --action [[1,0],[-1,0],[0,1],[0,-1],[0,0]] --ft-extr skin_cancer --batch-size 8 --nb-class 2 --img-size 256 -d 2 --nb 112 --na 112 --nd 16 --f 12 --nm 32 --nlb 160 --nla 160 --nb-epoch 50 --learning-rate 1e-4 -o ./out/skin_cancer_actor_critic
```

Note that beceause your dataset doesn't contain many observations, I have decreased the features/channels size in order to prevent overfitting.

The evaluation command :
```
python -m marl_classification --run-id test_skin_cancer -a 16 --step 16 --cuda test --batch-size 8 --dataset-path /home/samuel/PycharmProjects/MARLClassification/resources/downloaded/skin_cancer/ --json-path ./out/skin_cancer_actor_critic/marl.json --state-dict-path ./out/skin_cancer_actor_critic/models/nn_models_epoch_49.pt -o ./out/test_skin_cancer_actor_critic
```

The inference command :
```
python -m marl_classification --run-id infer_skin_cancer -a 16 --step 16 --cuda infer --images ./resources/downloaded/skin_cancer/melanoma/ISIC_0000013.jpg ./resources/downloaded/skin_cancer/benign/ISIC_0000008.jpg --json-path ./out/skin_cancer_actor_critic/marl.json --state-dict-path ./out/skin_cancer_actor_critic/models/nn_models_epoch_49.pt --class2idx ./out/skin_cancer_actor_critic/class_to_idx.json -o ./out/infer_skin_cancer_actor_critic
```

Let me know if it is working for you.

**Comment by Ipsedo** [comment] 2023-03-31 12:09
No response, I consider your issue as resolved

**Closed as completed by Ipsedo** 2023-03-31 12:09 UTC

**Comment by saptab** [comment] 2024-02-29 05:51
> Hi @Ipsedo
> 
> Pls find below link for the skin_cancer dataset we have used: https://drive.google.com/drive/folders/17g6zFSbCNXTV3VaDKop73W7Cn-NJlTO7?usp=sharing
> 
> here is the drive link for modified code and dataset: https://drive.google.com/drive/folders/15e79yCTh50GVrB9bNjT6LIiLsCB6X4nY?usp=share_link
> 
> We are using the cnn architecture as below in the CNNftExtractor file, < class SkinCancerCnn(CNNFtExtract):
> 
> ```
> def __init__(self, f: int) -> None:
>     super().__init__()
> 
>     self.__seq_conv = nn.Sequential(
>         nn.Conv2d(3, 16, kernel_size=(3, 3), padding=1),
>         nn.ReLU(),
>         nn.MaxPool2d(2, 2),
>         nn.Conv2d(16, 32, kernel_size=(3, 3), padding=1),
>         nn.ReLU(),
>         nn.MaxPool2d(2, 2),
>         nn.Conv2d(32, 64, kernel_size=(3, 3), padding=1),
>         nn.ReLU(),
>         nn.MaxPool2d(2, 2),
>         />
> ```
> 
> Here is the command I am using for model training < $ python -m marl_classification -a 10 --step 16 --cuda --run-id train_skin_cancer train --action [[1,0],[-1,0],[0,1],[0,-1]] --ft-extr skin_cancer --batch-size 8 --nb-class 2 --img-size 256 -d 2 --nb 192 --na 192 --nd 16 --f 12 --nm 64 --nlb 256 --nla 256 --nb-epoch 50 --learning-rate 1e-4 --eps 1.0 --eps-dec 0.99995 -o ./out/resisc45 />
> 
> but getting the below issue in the LSTM layer:
> 
> /usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 6 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary. warnings.warn(_create_warning_msg( 0% 0/61 [00:04<?, ?it/s] Traceback (most recent call last): File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/**main**.py", line 348, in main() File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/**main**.py", line 296, in main train(main_options, train_options) File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/train.py", line 187, in train pred, log_proba, _ = detailed_episode( File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/environment/episode.py", line 85, in detailed_episode agents.step(img_batch, eps) File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/environment/agent.py", line 177, in step h_t_next, c_t_next = self.__networks( File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/networks/models.py", line 87, in forward return self.__networks_dict[op](*args) File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/content/drive/MyDrive/assignments/utd/MARLClassification/marl_classification/networks/recurrents.py", line 41, in forward h_next, c_next = self.__lstm(u, (h, c)) File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/rnn.py", line 1194, in forward ret = _VF.lstm_cell( RuntimeError: input has inconsistent input_size: got 56 expected 24
> 
> Pls let us know what we can change Thank you.

Hi Zeeshan,

Could you please share your source of the dataset?

Thank you.
